const db=window.db,app=document.getElementById("app");
const S={route:null,instructor:null,school:null,profile:null,student:null,linked:null,instructorSelf:null,view:"dashboard",selected:new Date(),week:new Date(),hours:[],bookings:[],blocked:[]};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const pad=n=>String(n).padStart(2,"0");
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
const same=(a,b)=>iso(a)===iso(b);
function week(d){let x=new Date(d);x.setHours(0,0,0,0);let day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x}
function route(){let p=location.pathname.split("/").filter(Boolean);return p[0]==="i"&&p[1]?{type:"instructor",slug:p[1]}:p[0]==="s"&&p[1]?{type:"school",slug:p[1]}:{type:"home"}}
async function context(){S.route=route();if(S.route.type==="instructor"){let r=await db.from("instructors").select("id,slug,display_name,car,active,school_id,schools(id,name,slug)").eq("slug",S.route.slug).maybeSingle();S.instructor=r.data||null;S.school=r.data?.schools||null}if(S.route.type==="school"){let r=await db.from("schools").select("*").eq("slug",S.route.slug).maybeSingle();S.school=r.data||null}}
async function session(){let {data:{session}}=await db.auth.getSession();S.profile=null;S.student=null;S.linked=null;S.instructorSelf=null;if(!session)return;let p=await db.from("profiles").select("id,role,full_name,phone").eq("id",session.user.id).maybeSingle();S.profile=p.data;if(S.profile?.role==="student"){let s=await db.from("students").select("*").eq("profile_id",S.profile.id).maybeSingle();S.student=s.data;if(s.data){let r=await db.from("student_instructors").select("instructor_id,instructors(id,slug,display_name,car,active,school_id,schools(id,name,slug))").eq("student_id",s.data.id);S.linked=r.data?.[0]?.instructors||null}}if(S.profile?.role==="instructor"){let r=await db.from("instructors").select("id,slug,display_name,car,active,school_id,schools(id,name,slug)").eq("profile_id",session.user.id).maybeSingle();S.instructorSelf=r.data||null}}
async function finish(){if(!S.profile||S.profile.role!=="student"||S.student)return;let {data:{session}}=await db.auth.getSession();if(!session)return;let m=session.user.user_metadata||{},o=m.onboarding||{},iid=S.instructor?.id,sid=S.instructor?.school_id||S.school?.id||null;if(!iid&&o.instructorSlug){let r=await db.from("instructors").select("id,school_id").eq("slug",o.instructorSlug).maybeSingle();iid=r.data?.id;sid=sid||r.data?.school_id}if(!sid&&o.schoolSlug){let r=await db.from("schools").select("id").eq("slug",o.schoolSlug).maybeSingle();sid=r.data?.id}let r=await db.from("students").insert({profile_id:session.user.id,school_id:sid}).select().single();S.student=r.data|| (await db.from("students").select("*").eq("profile_id",session.user.id).maybeSingle()).data;if(S.student&&iid)await db.from("student_instructors").upsert({student_id:S.student.id,instructor_id:iid})}
async function active(i){let r=await db.from("subscriptions").select("status,expires_at").eq("instructor_id",i).eq("status","active").order("expires_at",{ascending:false}).limit(1).maybeSingle();return !!r.data&&(!r.data.expires_at||new Date(r.data.expires_at)>new Date())}
function toast(t,b=false){let x=document.createElement("div");x.className="toast "+(b?"bad":"");x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),3000)}
function layout(t,b){return `<div class="app-shell"><aside class="sidebar"><div class="logo">Drive<span>Pro</span></div><nav><button class="${S.view==="dashboard"?"active":""}" onclick="nav('dashboard')">⌂ <span>Обзор</span></button><button class="${S.view==="calendar"?"active":""}" onclick="nav('calendar')">▣ <span>Расписание</span></button><button class="${S.view==="bookings"?"active":""}" onclick="nav('bookings')">◫ <span>Мои занятия</span></button><button onclick="nav('notifications')">♧ <span>Уведомления</span></button><button onclick="nav('profile')">◯ <span>Профиль</span></button></nav><button class="logout" onclick="logout()">↪ <span>Выйти</span></button></aside><main class="main"><header class="topbar"><div><div class="eyebrow">DRIVEPRO</div><h1>${esc(t)}</h1>${t==="Расписание"?'<p class="subtitle">Выберите удобную дату и время для занятия</p>':""}</div><div class="user-chip">${esc(S.profile?.full_name||"")}</div></header>${b}</main></div>`}
function guest(){let t=S.instructor?`Вы записываетесь к ${esc(S.instructor.display_name)}`:"Начните обучение с DrivePro";app.innerHTML=`<div class="landing"><div class="landing-card"><div class="logo">Drive<span>Pro</span></div><h1>${t}</h1><p>Курсант пользуется DrivePro бесплатно.</p><div class="actions"><button class="primary" onclick="auth(true)">Зарегистрироваться</button><button onclick="auth(false)">Войти</button></div></div></div>`}
function auth(reg){app.innerHTML=`<div class="landing"><div class="auth-card"><div class="logo">Drive<span>Pro</span></div><h2>${reg?"Создание аккаунта":"Вход"}</h2>${reg?'<label>ФИО<input id="name"></label><label>Телефон<input id="phone"></label>':""}<label>Email<input id="email" type="email"></label><label>Пароль<input id="pass" type="password"></label><button class="primary full" onclick="${reg?"signup()":"signin()"}">${reg?"Создать аккаунт":"Войти"}</button><button class="secondary full" onclick="${reg?"auth(false)":"auth(true)"}">${reg?"У меня уже есть аккаунт":"Создать аккаунт"}</button><p id="msg"></p></div></div>`}
async function signup(){let n=name.value.trim(),p=phone.value.trim(),e=email.value.trim(),pw=pass.value;if(!n||!e||pw.length<6)return msg("Заполните данные. Пароль минимум 6 символов.",1);let onboarding={type:S.route.type,instructorSlug:S.route.type==="instructor"?S.route.slug:null,schoolSlug:S.route.type==="school"?S.route.slug:null};let r=await db.auth.signUp({email:e,password:pw,options:{data:{full_name:n,phone:p,role:"student",onboarding}}});if(r.error)return msg(r.error.message,1);if(r.data.session){await session();await finish();await session();S.view="dashboard";render()}else msg("Аккаунт создан. Подтвердите email, затем войдите.")}
async function signin(){let r=await db.auth.signInWithPassword({email:email.value.trim(),password:pass.value});if(r.error)return msg(r.error.message,1);await session();await finish();await session();render()}
function msg(t,b){let x=document.getElementById("msg");if(x){x.textContent=t;x.className=b?"error":"success"}}
async function loadData(i){let a=await db.from("instructor_working_hours").select("*").eq("instructor_id",i);let b=await db.from("bookings").select("id,student_id,instructor_id,starts_at,ends_at,status,lesson_type,lesson_count,booking_group_id").eq("instructor_id",i).gte("starts_at",new Date(new Date().getFullYear(),new Date().getMonth()-1,1).toISOString());S.hours=a.data||[];S.bookings=b.data||[]}
function bookingEnd(b){let start=new Date(b.starts_at),end=b.ends_at?new Date(b.ends_at):new Date(start.getTime()+(Number(b.lesson_count)||1)*45*60000);return end}
function overlaps(aStart,aEnd,bStart,bEnd){return aStart<bEnd&&aEnd>bStart}
function slot(d){let start=new Date(d),end=new Date(start.getTime()+45*60000),w=wh(start);if(!w)return"closed";let st=String(w.start_time).slice(0,5),en=String(w.end_time).slice(0,5),t=`${pad(start.getHours())}:${pad(start.getMinutes())}`;if(t<st||end>new Date(start.getFullYear(),start.getMonth(),start.getDate(),+String(w.end_time).slice(0,2),+String(w.end_time).slice(3,5),0,0))return"closed";let lunchStart=new Date(start);lunchStart.setHours(+String(w.lunch_start).slice(0,2),+String(w.lunch_start).slice(3,5),0,0);let lunchEnd=new Date(start);lunchEnd.setHours(+String(w.lunch_end).slice(0,2),+String(w.lunch_end).slice(3,5),0,0);if(overlaps(start,end,lunchStart,lunchEnd))return"lunch";if(S.blocked.some(x=>Math.abs(new Date(x.starts_at)-start)<60000))return"blocked";return S.bookings.some(b=>b.status==="confirmed"&&overlaps(start,end,new Date(b.starts_at),bookingEnd(b)))?"busy":"free"}
function daySlots(date){let out=[],d=new Date(date);d.setHours(7,0,0,0);while(d.getHours()<19){out.push(new Date(d));d=new Date(d.getTime()+45*60000)}return out}
function wh(d){return S.hours.find(x=>Number(x.day_of_week)===d.getDay()&&x.active)}
function mini(){let y=S.selected.getFullYear(),m=S.selected.getMonth(),f=new Date(y,m,1),start=(f.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),html="";for(let i=0;i<start;i++)html+=`<button class="day muted-day" disabled>${new Date(y,m,0).getDate()-start+i+1}</button>`;for(let n=1;n<=days;n++){let d=new Date(y,m,n),has=daySlots(d).some(x=>slot(x)==="free")&&! (d<new Date(iso(new Date())));html+=`<button class="day ${same(d,S.selected)?"selected":""} ${has?"has-free":""}" onclick="pick(${y},${m},${n})">${n}${has?"<i></i>":""}</button>`}return `<div class="month-head"><button onclick="month(-1)">‹</button><h2>${S.selected.toLocaleDateString("ru-RU",{month:"long",year:"numeric"})}</h2><button onclick="month(1)">›</button></div><div class="weekdays"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Вс</span></div><div class="days">${html}</div><div class="legend"><div><i class="dot green"></i>Есть свободные слоты</div><div><i class="dot gray"></i>Нет доступных слотов</div><div><i class="dot blue"></i>Выбранная дата</div></div><div class="info-box"><b>График занятий</b><p>07:00 — 19:00</p><p>Обед: 12:00 — 13:00</p><p>Длительность: 45 минут</p></div>`}
function grid(){let ds=[0,1,2,3,4,5,6].map(i=>add(S.week,i)),slots=daySlots(S.week),html=`<div class="grid-wrap"><div class="time-head">Время</div>${ds.map(d=>`<div class="date-head ${same(d,S.selected)?"today-col":""}"><b>${d.toLocaleDateString("ru-RU",{weekday:"short"})}</b><small>${d.getDate()} ${d.toLocaleDateString("ru-RU",{month:"short"})}</small></div>`).join("")}`;for(let base of slots){html+=`<div class="time-cell">${pad(base.getHours())}:${pad(base.getMinutes())}</div>`;for(let day of ds){let x=new Date(day);x.setHours(base.getHours(),base.getMinutes(),0,0),st=slot(x),past=x<new Date(),b=S.bookings.find(y=>y.status==="confirmed"&&overlaps(x,new Date(x.getTime()+45*60000),new Date(y.starts_at),bookingEnd(y)));if(st==="lunch")html+='<button class="slot lunch" disabled>Обед</button>';else if(st==="busy")html+=`<button class="slot busy" disabled>${b?.lesson_count>1?"Занято":"Занято"}</button>`;else if(st==="blocked"||st==="closed"||past)html+='<button class="slot closed" disabled>—</button>';else html+=`<button class="slot free ${same(day,S.selected)?"selected-col":""}" onclick="book('${iso(day)}',${base.getHours()},${base.getMinutes()})">Свободно</button>`}}return html+"</div><div class=\"legend bottom\"><span><i class=\"dot green\"></i>Свободно</span><span><i class=\"dot blue\"></i>Занято</span><span><i class=\"dot red\"></i>Обед (12:00 — 13:00)</span><span><i class=\"dot gray\"></i>Недоступно</span></div>"}
async function loadReviews(instructorId){
  let r=await db.from("reviews").select("id,rating,text,created_at,student_id,students(profiles(full_name))")
    .eq("instructor_id",instructorId).order("created_at",{ascending:false});
  return r.data||[];
}
async function submitReview(){
  if(!S.student)return toast("Войдите в аккаунт.",1);
  let ins=S.linked||S.instructor;
  let rating=Number(document.getElementById("review-rating")?.value||0);
  let text=document.getElementById("review-text")?.value.trim()||"";
  if(!rating)return toast("Выберите оценку от 1 до 5.",1);
  if(text.length<5)return toast("Напишите отзыв минимум из 5 символов.",1);
  let r=await db.from("reviews").upsert(
    {student_id:S.student.id,instructor_id:ins.id,rating,text},
    {onConflict:"student_id,instructor_id"}
  );
  if(r.error)return toast(r.error.message,1);
  toast("Спасибо! Ваш отзыв сохранён."); render();
}
async function reviewsBlock(ins){
  let rows=await loadReviews(ins.id);
  let mine=rows.find(x=>x.student_id===S.student?.id);
  let avg=rows.length?(rows.reduce((a,x)=>a+Number(x.rating),0)/rows.length).toFixed(1):"—";
  let list=rows.slice(0,6).map(x=>{
    let name=x.student_id===S.student?.id?"Вы":(x.students?.profiles?.full_name||"Курсант");
    return `<div class="review-item"><div class="review-top"><b>${esc(name)}</b><span class="stars">${"★".repeat(Number(x.rating))}${"☆".repeat(5-Number(x.rating))}</span></div><p>${esc(x.text)}</p><small>${new Date(x.created_at).toLocaleDateString("ru-RU")}</small></div>`;
  }).join("");
  return `<section class="reviews card">
    <div class="reviews-head"><div><span class="blue-label">Отзывы</span><h2>Отзывы о ${esc(ins.display_name)}</h2></div>
    <div class="rating-big"><b>${avg}</b><span>★</span><small>${rows.length} ${rows.length===1?"отзыв":"отзывов"}</small></div></div>
    <div class="review-form"><h3>${mine?"Изменить отзыв":"Оставить отзыв"}</h3>
      <label>Оценка<select id="review-rating"><option value="">Выберите оценку</option>
      ${[5,4,3,2,1].map(n=>`<option value="${n}" ${mine?.rating===n?"selected":""}>${n} — ${"★".repeat(n)}${"☆".repeat(5-n)}</option>`).join("")}</select></label>
      <textarea id="review-text" rows="3" maxlength="500" placeholder="Расскажите о занятиях с инструктором...">${esc(mine?.text||"")}</textarea>
      <button class="primary" onclick="submitReview()">${mine?"Сохранить изменения":"Опубликовать отзыв"}</button>
    </div>
    <div class="review-list">${list||'<div class="empty">Пока нет отзывов. Будьте первым.</div>'}</div>
  </section>`;
}

function instructorLayout(t,b){return `<div class="app-shell instructor-shell"><aside class="sidebar"><div class="logo">Drive<span>Pro</span></div><nav><button class="${S.view==="dashboard"?"active":""}" onclick="nav('dashboard')">⌂ <span>Обзор</span></button><button class="${S.view==="instructor-calendar"?"active":""}" onclick="nav('instructor-calendar')">▣ <span>Расписание</span></button><button class="${S.view==="students"?"active":""}" onclick="nav('students')">♙ <span>Курсанты</span></button><button class="${S.view==="instructor-bookings"?"active":""}" onclick="nav('instructor-bookings')">◫ <span>Мои занятия</span></button><button class="${S.view==="reviews"?"active":""}" onclick="nav('reviews')">★ <span>Отзывы</span></button><button class="${S.view==="subscription"?"active":""}" onclick="nav('subscription')">₸ <span>Подписка</span></button><button class="${S.view==="profile"?"active":""}" onclick="nav('profile')">◯ <span>Профиль</span></button></nav><button class="logout" onclick="logout()">↪ <span>Выйти</span></button></aside><main class="main"><header class="topbar"><div><div class="eyebrow">DRIVEPRO · ИНСТРУКТОР</div><h1>${esc(t)}</h1></div><div class="user-chip">${esc(S.profile?.full_name||S.instructorSelf?.display_name||"")}</div></header>${b}</main></div>`}
async function instructorData(){let i=S.instructorSelf;if(!i)return;let from=new Date();from.setHours(0,0,0,0);let to=new Date(from);to.setDate(to.getDate()+14);let [h,b,bl,rv]=await Promise.all([db.from("instructor_working_hours").select("*").eq("instructor_id",i.id),db.from("bookings").select("id,student_id,starts_at,ends_at,status,lesson_type,lesson_count,booking_group_id,students(profiles(full_name,phone))").eq("instructor_id",i.id).gte("starts_at",from.toISOString()).lt("starts_at",to.toISOString()).order("starts_at"),db.from("instructor_blocked_slots").select("id,starts_at,reason").eq("instructor_id",i.id).gte("starts_at",from.toISOString()).lt("starts_at",to.toISOString()),db.from("reviews").select("rating").eq("instructor_id",i.id)]);S.hours=h.data||[];S.bookings=b.data||[];S.blocked=bl.data||[];S.reviewCount=rv.data?.length||0;S.reviewAvg=S.reviewCount?(rv.data.reduce((a,x)=>a+Number(x.rating),0)/S.reviewCount).toFixed(1):"—"}
function instructorSlotState(d){let start=new Date(d),end=new Date(start.getTime()+45*60000),w=S.hours.find(x=>Number(x.day_of_week)===start.getDay()&&x.active);if(!w)return"closed";let st=String(w.start_time).slice(0,5),en=String(w.end_time).slice(0,5),t=`${pad(start.getHours())}:${pad(start.getMinutes())}`;if(t<st||end>new Date(start.getFullYear(),start.getMonth(),start.getDate(),+String(w.end_time).slice(0,2),+String(w.end_time).slice(3,5),0,0))return"closed";let ls=new Date(start);ls.setHours(+String(w.lunch_start).slice(0,2),+String(w.lunch_start).slice(3,5),0,0);let le=new Date(start);le.setHours(+String(w.lunch_end).slice(0,2),+String(w.lunch_end).slice(3,5),0,0);if(overlaps(start,end,ls,le))return"lunch";if(S.blocked.some(x=>Math.abs(new Date(x.starts_at)-start)<60000))return"blocked";return S.bookings.some(x=>x.status==="confirmed"&&overlaps(start,end,new Date(x.starts_at),bookingEnd(x)))?"busy":"free"}
function instructorDaySlots(date){return daySlots(date)}
async function renderInstructorDashboard(){await instructorData();let today=new Date(),todayBookings=S.bookings.filter(x=>same(new Date(x.starts_at),today)&&x.status==="confirmed"),upcoming=S.bookings.filter(x=>new Date(x.starts_at)>=new Date()&&x.status==="confirmed").sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at))[0],uniqueStudents=new Set(S.bookings.map(x=>x.student_id)).size;let next=upcoming?`<div class="next-booking"><div class="next-date">${esc(new Date(upcoming.starts_at).toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"}))}</div><h2>${esc(formatBookingRange(upcoming.starts_at,undefined,upcoming.lesson_count,upcoming.ends_at))}</h2><p>${esc(upcoming.students?.profiles?.full_name||"Курсант")} · ${esc(upcoming.students?.profiles?.phone||S.instructorSelf.car||"")}</p><span class="status ok">${upcoming.lesson_count>1?`${upcoming.lesson_count} академических часа`:`1 академический час`}</span></div>`:`<div class="empty">На ближайшее время записей нет.</div>`;let timeline=instructorDaySlots(today).map(d=>{let st=instructorSlotState(d),b=S.bookings.find(x=>x.status==="confirmed"&&overlaps(d,new Date(d.getTime()+45*60000),new Date(x.starts_at),bookingEnd(x)));return `<div class="mini-time"><b>${pad(d.getHours())}:${pad(d.getMinutes())}</b><div class="mini-state ${st}">${st==="busy"?esc(b?.students?.profiles?.full_name||"Курсант"):st==="lunch"?"Обед":st==="free"?"Свободно":st==="blocked"?"Закрыто":"—"}</div></div>`}).join("");app.innerHTML=instructorLayout(`Добрый день, ${S.profile?.full_name?.split(" ")[0]||"инструктор"}`,`<div class="stats-grid"><section class="stat-card"><span>Сегодня</span><b>${todayBookings.length}</b><small>занятий</small></section><section class="stat-card"><span>Курсанты</span><b>${uniqueStudents}</b><small>за ближайшие 14 дней</small></section><section class="stat-card"><span>Рейтинг</span><b>★ ${esc(S.reviewAvg)}</b><small>${S.reviewCount} отзывов</small></section><section class="stat-card"><span>Ссылка</span><b class="stat-link">/i/${esc(S.instructorSelf.slug)}</b><small>ваша ссылка</small></section></div><div class="instructor-dashboard-grid"><section class="card"><div class="section-head"><div><span class="blue-label">БЛИЖАЙШЕЕ</span><h2>Ближайшее занятие</h2></div><button onclick="nav('instructor-bookings')">Все занятия</button></div>${next}</section><section class="card"><div class="section-head"><div><span class="blue-label">СЕГОДНЯ</span><h2>График</h2></div><button class="primary" onclick="nav('instructor-calendar')">Открыть расписание</button></div><div class="mini-timeline">${timeline}</div></section></div><section class="card instructor-note"><b>Рабочий график</b><span>07:00–19:00 · обед 12:00–13:00 · академический час 45 минут</span></section>`)}
async function renderInstructorCalendar(){await instructorData();let days=[0,1,2,3,4,5,6].map(i=>add(S.week,i));let rows=instructorDaySlots(S.week).map(d=>{let h=d.getHours(),m=d.getMinutes(),cells=days.map(day=>{let x=new Date(day);x.setHours(h,m,0,0);let st=instructorSlotState(x),b=S.bookings.find(y=>y.status==="confirmed"&&overlaps(x,new Date(x.getTime()+45*60000),new Date(y.starts_at),bookingEnd(y)));return `<button class="islot ${st}" ${st==="free"?`onclick="blockInstructorSlot('${x.toISOString()}')"`:""}>${st==="busy"?esc(b?.students?.profiles?.full_name||"Занято"):st==="lunch"?"Обед":st==="blocked"?"Закрыто":st==="free"?"Свободно":"—"}</button>`}).join("");return `<div class="itime">${pad(h)}:${pad(m)}</div>${cells}`}).join("");app.innerHTML=instructorLayout("Расписание",`<section class="card"><div class="section-head"><div><span class="blue-label">НЕДЕЛЯ</span><h2>${esc(S.week.toLocaleDateString("ru-RU",{day:"numeric",month:"long"}))}</h2></div><div class="week-actions"><button onclick="moveInstructorWeek(-7)">‹</button><button onclick="todayInstructor()">Сегодня</button><button onclick="moveInstructorWeek(7)">›</button></div></div><div class="instructor-grid"><div class="itime head">Время</div>${days.map(d=>`<div class="idate ${same(d,new Date())?"today-col":""}"><b>${esc(d.toLocaleDateString("ru-RU",{weekday:"short"}))}</b><small>${d.getDate()} ${esc(d.toLocaleDateString("ru-RU",{month:"short"}))}</small></div>`).join("")}${rows}</div><div class="legend bottom"><span><i class="dot green"></i>Свободно</span><span><i class="dot blue"></i>Занято</span><span><i class="dot red"></i>Обед</span><span><i class="dot gray"></i>Закрыто</span></div><p class="schedule-note">Нажмите на свободный слот, чтобы временно закрыть его.</p></section>`)}
async function blockInstructorSlot(isoTime){let d=new Date(isoTime);if(!confirm(`Закрыть слот ${d.toLocaleString("ru-RU")}?`))return;let r=await db.from("instructor_blocked_slots").insert({instructor_id:S.instructorSelf.id,starts_at:d.toISOString(),reason:"Закрыто инструктором"});if(r.error)return toast(r.error.message,1);toast("Слот закрыт.");renderInstructorCalendar()}
function moveInstructorWeek(n){S.week=add(S.week,n);renderInstructorCalendar()}function todayInstructor(){S.week=week(new Date());renderInstructorCalendar()}
async function renderInstructorBookings(){await instructorData();let rows=[...S.bookings].sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));app.innerHTML=instructorLayout("Мои занятия",`<section class="card"><div class="section-head"><div><span class="blue-label">ЗАПИСИ</span><h2>Занятия курсантов</h2></div></div>${rows.length?rows.map(b=>{let st=new Date(b.starts_at),en=bookingEnd(b);return `<div class="instructor-booking-row"><div class="booking-time"><b>${esc(st.toLocaleDateString("ru-RU",{day:"numeric",month:"short"}))}</b><strong>${pad(st.getHours())}:${pad(st.getMinutes())}–${pad(en.getHours())}:${pad(en.getMinutes())}</strong></div><div><h3>${esc(b.students?.profiles?.full_name||"Курсант")}</h3><p>${b.lesson_type==="autodrome"?"Автодром":"Город"} · ${b.lesson_count>1?`${b.lesson_count} академических часа`:`1 академический час`}</p></div><span class="status ok">Подтверждено</span></div>`}).join(""):'<div class="empty">Занятий пока нет.</div>'}</section>`)}
async function renderInstructorStudents(){await instructorData();let ids=[...new Set(S.bookings.map(x=>x.student_id))],rows=ids.map(id=>S.bookings.find(x=>x.student_id===id)).filter(Boolean);app.innerHTML=instructorLayout("Курсанты",`<section class="card"><div class="section-head"><div><span class="blue-label">МОИ КУРСАНТЫ</span><h2>Курсанты</h2></div><span class="muted">${ids.length} чел.</span></div>${rows.length?rows.map(b=>{let count=S.bookings.filter(x=>x.student_id===b.student_id).length;return `<div class="student-row"><div class="student-avatar">${esc((b.students?.profiles?.full_name||"К")[0])}</div><div><h3>${esc(b.students?.profiles?.full_name||"Курсант")}</h3><p>${esc(b.students?.profiles?.phone||"")}${b.students?.profiles?.phone?" · ":""}${count} занятий в ближайшие 14 дней</p></div></div>`}).join(""):'<div class="empty">Курсанты появятся после первой записи.</div>'}</section>`)}
async function renderInstructorReviews(){let r=await db.from("reviews").select("rating,text,created_at,students(profiles(full_name))").eq("instructor_id",S.instructorSelf.id).order("created_at",{ascending:false}),data=r.data||[],avg=data.length?(data.reduce((a,x)=>a+Number(x.rating),0)/data.length).toFixed(1):"—";app.innerHTML=instructorLayout("Отзывы",`<section class="card reviews"><div class="reviews-head"><div><span class="blue-label">ОТЗЫВЫ</span><h2>Отзывы курсантов</h2></div><div class="rating-big"><b>${avg}</b><span>★</span><small>${data.length} отзывов</small></div></div>${data.length?data.map(x=>`<div class="review-item"><div class="review-top"><b>${esc(x.students?.profiles?.full_name||"Курсант")}</b><span class="stars">${"★".repeat(Number(x.rating))}${"☆".repeat(5-Number(x.rating))}</span></div><p>${esc(x.text)}</p><small>${new Date(x.created_at).toLocaleDateString("ru-RU")}</small></div>`).join(""):'<div class="empty">Пока нет отзывов.</div>'}</section>`)}
async function renderInstructorSubscription(){let r=await db.from("subscriptions").select("status,expires_at").eq("instructor_id",S.instructorSelf.id).order("expires_at",{ascending:false}).limit(1).maybeSingle(),ok=r.data&&r.data.status==="active"&&(!r.data.expires_at||new Date(r.data.expires_at)>new Date());app.innerHTML=instructorLayout("Подписка",`<section class="card subscription-card"><span class="blue-label">DRIVEPRO</span><h2>Подписка инструктора</h2><div class="subscription-status ${ok?"sub-active":"sub-off"}">${ok?"Активна":"Неактивна"}</div><div class="price-row"><div><span>Подключение</span><b>15 000 ₸</b></div><div><span>Ежемесячно</span><b>2 990 ₸</b></div></div><p class="muted">${ok&&r.data.expires_at?`Действует до ${new Date(r.data.expires_at).toLocaleDateString("ru-RU")}:`:'После активации курсанты смогут записываться на ваши занятия.'}</p></section>`)}
async function renderCalendar(){
  let ins=S.linked||S.instructor;
  if(!ins)return app.innerHTML=layout("Расписание",'<div class="card empty">Инструктор не выбран.</div>');
  await loadData(ins.id);
  if(!await active(ins.id))return app.innerHTML=layout("Расписание",'<div class="card notice">Данный инструктор временно не принимает записи на занятия.</div>');
  S.week=week(S.selected);
  app.innerHTML=layout("Расписание",`<section class="instructor-card">
    <div class="instructor-main"><div class="car-placeholder">🚗</div><div><span class="blue-label">Инструктор</span><h2>${esc(ins.display_name)}</h2><p>${esc(ins.car||"")}</p></div></div>
    <div class="meta-block"><span>Автомобиль</span><b>${esc(ins.car||"")}</b></div>
    <div class="meta-block"><span>График</span><b>07:00 — 19:00</b><small>Обед: 12:00 — 13:00</small></div>
    <div class="meta-block"><span>Статус</span><strong class="status ok">Принимает записи</strong></div>
    <div class="meta-block"><span>Ваша ссылка</span><div class="link-box">/i/${esc(ins.slug)} <button onclick="copyLink()">⧉</button></div></div>
  </section>
  <div class="schedule-layout"><aside class="calendar-side">${mini()}</aside>
    <section class="week-panel"><div class="week-head"><h2>${esc(S.selected.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long",year:"numeric"}))}</h2>
      <div class="week-actions"><button onclick="move(-7)">‹</button><button onclick="move(7)">›</button><button onclick="today()">Сегодня</button></div>
    </div>${grid()}<div class="schedule-note">Нажмите на зелёный слот, чтобы записаться.</div></section>
  </div>${await reviewsBlock(ins)}`);
}

async function openBooking(date,h,m=0){
  if(!S.student)return toast("Войдите в аккаунт.",1);
  let ins=S.linked||S.instructor;
  let d=new Date(`${date}T${pad(h)}:${pad(m)}:00`);
  if(d.getHours()<7||d.getHours()>=19)return toast("Запись доступна с 07:00 до 19:00.",1);
  document.getElementById("booking-modal")?.remove();
  window.__bookingDate=date;window.__bookingHour=h;window.__bookingMinute=m;
  let html=`<div class="modal-backdrop" id="booking-modal"><div class="booking-modal"><button class="modal-close" onclick="closeBooking()">×</button><span class="blue-label">НОВАЯ ЗАПИСЬ</span><h2>Запись на занятие</h2><div class="booking-summary"><b>${esc(ins.display_name)}</b><span>${d.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})} · начало в ${pad(h)}:${pad(m)}</span></div><label>Тип занятия<select id="lesson-type" onchange="toggleAutodromeWarning()"><option value="city">Город</option><option value="autodrome">Автодром</option></select></label><label>Количество академических часов<select id="lesson-count" onchange="toggleAutodromeWarning()"><option value="1">1 час — 45 минут</option><option value="2">2 часа — 90 минут</option></select></label><div id="autodrome-warning" class="autodrome-warning hidden"><b>Важно для автодрома</b><p>Для занятия на автодроме необходимо записываться минимум на <strong>2 академических часа подряд</strong>.</p><p>Система забронирует единый интервал 90 минут.</p></div><div id="booking-preview" class="booking-preview"></div><div class="modal-actions"><button class="secondary" onclick="closeBooking()">Отмена</button><button class="primary" onclick="confirmBooking('${date}',${h},${m})">Подтвердить запись</button></div></div></div>`;
  document.body.insertAdjacentHTML("beforeend",html);toggleAutodromeWarning();
}
function formatBookingRange(date,h,n,existingEnd){let start;if(date instanceof Date)start=new Date(date);else if(typeof date==="string"&&h!==undefined)start=new Date(`${date}T${pad(h)}:${pad(window.__bookingMinute||0)}:00`);else start=new Date(date);let end=existingEnd?new Date(existingEnd):new Date(start.getTime()+(Number(n)||1)*45*60000);return `${pad(start.getHours())}:${pad(start.getMinutes())}–${pad(end.getHours())}:${pad(end.getMinutes())}`}
function toggleAutodromeWarning(){let type=document.getElementById("lesson-type")?.value,count=document.getElementById("lesson-count"),warning=document.getElementById("autodrome-warning");if(!count)return;if(type==="autodrome"){count.value="2";[...count.options].forEach(o=>o.disabled=o.value!=="2");warning.classList.remove("hidden")}else{[...count.options].forEach(o=>o.disabled=false);warning.classList.add("hidden")}let n=Number(count.value||1),date=window.__bookingDate,h=window.__bookingHour,m=window.__bookingMinute||0;if(date&&h!==undefined)document.getElementById("booking-preview").innerHTML=`Будет занято: <strong>${formatBookingRange(date,h,n)}</strong> · ${n} ${n===1?"академический час":"академических часа"}.`}
function closeBooking(){document.getElementById("booking-modal")?.remove()}
async function confirmBooking(date,h,m=0){let type=document.getElementById("lesson-type").value,count=Number(document.getElementById("lesson-count").value);if(type==="autodrome"&&count<2)return toast("Для автодрома нужно выбрать 2 академических часа.",1);let ins=S.linked||S.instructor,first=new Date(`${date}T${pad(h)}:${pad(m)}:00`),end=new Date(first.getTime()+count*45*60000);if(end.getHours()>19||(end.getHours()===19&&end.getMinutes()>0))return toast("Занятие не может заканчиваться позже 19:00.",1);for(let k=0;k<count;k++){let d=new Date(first.getTime()+k*45*60000),st=slot(d);if(st!=="free")return toast(`Время ${pad(d.getHours())}:${pad(d.getMinutes())} недоступно. Выберите другой слот.`,1)}if(!confirm(`Подтвердить запись: ${formatBookingRange(date,h,count)}?`))return;let row={student_id:S.student.id,instructor_id:ins.id,starts_at:first.toISOString(),ends_at:end.toISOString(),status:"confirmed",lesson_type:type,lesson_count:count,booking_group_id:crypto.randomUUID()};let r=await db.from("bookings").insert(row);if(r.error)return toast(r.error.code==="23P01"||r.error.code==="23505"?"Выбранное время уже занято. Выберите другой слот.":r.error.message,1);closeBooking();toast(`Записано: ${formatBookingRange(date,h,count)}.`);S.view="bookings";render()}
async function book(date,h,m=0){window.__bookingDate=date;window.__bookingHour=h;window.__bookingMinute=m;await openBooking(date,h,m)}
function pick(y,m,d){S.selected=new Date(y,m,d);S.week=week(S.selected);render()}function month(n){S.selected=new Date(S.selected.getFullYear(),S.selected.getMonth()+n,1);S.week=week(S.selected);render()}function move(n){S.week=add(S.week,n);S.selected=add(S.selected,n);render()}function today(){S.selected=new Date();S.week=week(S.selected);render()}function copyLink(){navigator.clipboard?.writeText(location.origin+"/i/"+(S.instructor||S.linked)?.slug);toast("Ссылка скопирована.")}
async function renderBookings(){let r=await db.from("bookings").select("id,starts_at,ends_at,status,lesson_type,lesson_count,instructors(display_name,car)").eq("student_id",S.student.id).order("starts_at",{ascending:true});app.innerHTML=layout("Мои занятия",`<section class="card">${r.data?.length?r.data.map(b=>{let st=new Date(b.starts_at),en=bookingEnd(b);return `<div class="notification"><b>${esc(b.instructors?.display_name)}</b><div>${esc(st.toLocaleDateString("ru-RU"))} · ${pad(st.getHours())}:${pad(st.getMinutes())}–${pad(en.getHours())}:${pad(en.getMinutes())} · ${b.lesson_type==="autodrome"?"Автодром":"Город"}</div><small class="muted">${b.lesson_count>1?"2 академических часа (90 минут)":"1 академический час (45 минут)"} · ${esc(b.instructors?.car||"")}</small><br><span class="status ok">${b.status==="confirmed"?"Подтверждено":"Отменено"}</span></div>`}).join(""):'<div class="empty">У вас пока нет занятий.</div>'}</section>`)}
function profile(){app.innerHTML=layout("Профиль",`<section class="card profile"><div class="avatar">${esc((S.profile.full_name||"Д")[0])}</div><h2>${esc(S.profile.full_name)}</h2><p>${esc(S.profile.phone||"")}</p><div class="free-box"><b>Курсант: 0 ₸</b><br>Подписка не требуется.</div></section>`)}
async function getNextBooking(){if(!S.student)return null;let r=await db.from("bookings").select("id,starts_at,ends_at,status,lesson_type,lesson_count,instructors(display_name,car)").eq("student_id",S.student.id).eq("status","confirmed").gte("starts_at",new Date().toISOString()).order("starts_at",{ascending:true}).limit(1).maybeSingle();return r.data||null}
async function render(){await context();await session();if(S.profile?.role==="instructor"){if(S.view==="instructor-calendar")return renderInstructorCalendar();if(S.view==="instructor-bookings")return renderInstructorBookings();if(S.view==="students")return renderInstructorStudents();if(S.view==="reviews")return renderInstructorReviews();if(S.view==="subscription")return renderInstructorSubscription();if(S.view==="profile")return app.innerHTML=instructorLayout("Профиль",`<section class="card profile"><div class="avatar">${esc((S.profile.full_name||"И")[0])}</div><h2>${esc(S.profile.full_name)}</h2><p>${esc(S.profile.phone||"")}</p><div class="free-box"><b>Ваша ссылка</b><br>/i/${esc(S.instructorSelf?.slug||"")}</div></section>`);return renderInstructorDashboard()}if(!S.profile)return guest();if(!S.student){await finish();await session()}if(S.view==="calendar")return renderCalendar();if(S.view==="bookings")return renderBookings();if(S.view==="profile")return profile();let next=await getNextBooking();let nextCard=next?`<span class="muted">Ближайшее занятие</span><div class="next-booking"><div class="next-date">${esc(new Date(next.starts_at).toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"}))}</div><h2>${esc(formatBookingRange(next.starts_at,undefined,next.lesson_count,next.ends_at))}</h2><p>${esc(next.instructors?.display_name||"Инструктор")} · ${esc(next.instructors?.car||"")}</p><span class="status ok">${next.lesson_count>1?`${next.lesson_count} академических часа`:"1 академический час"}</span><button class="primary small-btn" onclick="nav('bookings')">Подробнее</button></div>`:`<span class="muted">Ближайшее занятие</span><h2>Нет записи</h2><p class="muted">Выберите удобное время в расписании.</p><button class="primary" onclick="nav('calendar')">Записаться</button>`;app.innerHTML=layout("Кабинет курсанта",`<div class="cards"><section class="card"><span class="muted">Инструктор</span><h2>${esc((S.linked||S.instructor)?.display_name||"Не выбран")}</h2><p>${esc((S.linked||S.instructor)?.car||"")}</p></section><section class="card upcoming-card">${nextCard}</section><section class="card"><span class="muted">Стоимость для вас</span><h2>0 ₸</h2><p class="muted">DrivePro бесплатен для курсанта.</p></section></div>`)}
function nav(v){S.view=v;render()}async function logout(){await db.auth.signOut();S.view="dashboard";render()}db.auth.onAuthStateChange(()=>setTimeout(render,50));render();